### ISSUE TITLE
Freezing on vita using adrenaline

### ISSUE THREAD

**Issue by OmegaRobert** [cuevavirus/PSOneScrot#1]
Using 6.61 Adrenaline on system ver 3.60. When holding the PS button, the grey PSP menu appears (do you wish to exit the game) followed by the PS Vita menu. I can then access the official settings via the adrenaline settings menu, and take a screenshot, but on some occasions this leads to Adrenaline freezing when it returns to the game. I suspect that the grey PSP menu is still active in the background and unresponsive, as I've noticed this being glitchy in the past.

**Comment by cuevavirus** [comment]
From the way you describe it, isn't this an adrenaline bug?

**Comment by OmegaRobert** [comment]
To be honest, I wasn't entirely sure whether the issue was the plugin causing the freezing or Adrenaline. Judging by previous experiences, you're probably right!
