### ISSUE TITLE
SD2Vita card not  recognizing PSOneScrot.

### ISSUE THREAD

**Issue by Snailhail** [cuevavirus/PSOneScrot#2]
Hi cuevavirus, I'm using Henkaku on firmware 3.60 with a SD2Vita card 128gb card ( slot ux0: ) & unfortunately I can't  see the screenshot option & everything is installed correctly. I can tell because I used a memory card verison of my profile on the same ps1 game & It worked perfectly. Is there a workaround for this, or is it not supported by your plugin? My card is acknowledged  & other plugins work fine. So, I'm unsure where the problem lays & I tried  reboot/reload nothing as well. My tai folder is in ur0: If that helps.

**Comment by cuevavirus** [comment]
Place your sd2vita mounting plugin before psonescrot in config.txt. ux0 needs to be accessible when psonescrot is starting up.

**Comment by Snailhail** [comment]
Perfection! Amazing work with this plugin of yours.
 I got It working right away! Works either official, or ps1 Adrenaline.
